---
- name: Initialize Kubernetes Cluster
  hosts: k8s_master_main
  gather_facts: no
  remote_user: root
  tasks:
    - name: Reset Kubernetes Cluster
      shell: kubeadm reset -f

    - name: Initialize Kubernetes Cluster
      shell: kubeadm init --control-plane-endpoint=k8s-master-lb:6443 --upload-certs --pod-network-cidr=192.168.0.0/16 | tee ~/initial_log

    - name: Copy logs to Ansible server
      fetch:
        src: ~/initial_log
        dest: /sources/initial_log
        flat: yes
    
    - name: Delete logs
      file:
        path: ~/initial_log
        state: absent

    - name: Copy admin.conf to Ansible server
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /sources/admin.conf
        flat: yes  