---
- name: Install metrics-server
  hosts: k8s_master_main
  gather_facts: no
  remote_user: root
  tasks:
    - name: Copy install metrics-server script to host
      copy:
        src: ../install_metrics_server.sh
        dest: $HOME/
        mode: '0700'

    - name: install metrics-server
      command: $HOME/install_metrics_server.sh

    - name: Delete files
      file:
        path: $HOME/install_metrics_server.sh
        state: absent