---
- name: Install Keepalived for Master LoadBalancer
  hosts: k8s_lb_master
  gather_facts: no
  remote_user: root
  tasks:
    - name: Install Packages
      yum:
        name: keepalived
        state: present

    - name: Stat Configure file
      stat: path=/etc/keepalived/keepalived.conf.bak
      register: bak_stat

    - name: Backup Configure file
      command: mv /etc/keepalived/keepalived.conf /etc/keepalived/keepalived.conf.bak
      when: not bak_stat.stat.exists

    - name: Initialize Configure file
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent

    - name: Create Configure file
      file:
        path: /etc/keepalived/keepalived.conf
        state: touch

    - name: Configure VIP
      blockinfile:
        path: /etc/keepalived/keepalived.conf
        block: |
          global_defs {
              router_id K8S_LB1
          }

          vrrp_script chk_haproxy {
              script "killall -0 haproxy"
              interval 2
              weight 2
          }

          vrrp_instance VI_1 {
              state MASTER
              interface ens33
              virtual_router_id 33
              priority 100
              advert_int 1
              authentication {
                  auth_type PASS
                  auth_pass k8slb
              }

              virtual_ipaddress {
                  10.6.3.200
              }

              track_script {
                  chk_haproxy
              }
          }

    - name: Enable Service
      systemd:
        name: keepalived
        state: started
        enabled: yes