---
- name: Initialize Worker Nodes
  hosts: k8s_workers
  gather_facts: no
  remote_user: root
  tasks:
    - name: Reset Kubernetes
      shell: kubeadm reset -f
      
    - name: Copy Join Command
      copy:
        src: /sources/Worker
        dest: $HOME/
  
    - name: Join Kubernetes Cluster as Worker
      shell: $(cat $HOME/Worker)

    - name: Remove Join files
      file:
        path: $HOME/Worker
        state: absent