---
- name: ssh-keygen
  hosts: k8s-all
  gather_facts: no
  tasks:
    - name: create key
      connection: local
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
        size: 4096

    - name: input key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"