---
- name: Initialize system for install kubernetes
  hosts: k8s_all
  gather_facts: no
  remote_user: root
  tasks:  
    - name: Disable Swap (1/2)
      shell: |
        swapoff -a
    - name: Disable Swap (2/2)
      replace: 
        path: /etc/fstab
        regexp: '^([^#].*?\s[ns].*swap\s+.*)$'
        replace: '# \1'
    - name: Set Kernel Mode
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter
        create: true

    - name: Reload Kernel (1/2)
      modprobe:
        name: overlay
    - name: Reload Kernel (2/2)
      modprobe: 
        name: br_netfilter

    - name: Configure Kernel
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        create: true

    - name: Enable Kernel
      command: sysctl --system

    - name: Configure Kernel
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        create: true