---
- name: Initialize Master Nodes
  hosts: k8s_master_join
  gather_facts: no
  remote_user: root
  tasks:
    - name: Reset Kubernetes
      shell: kubeadm reset -f
      
    - name: Copy Join Command
      copy:
        src: /sources/Master
        dest: $HOME/
  
    - name: Join Kubernetes Cluster as Master
      shell: $(cat $HOME/Master)

    - name: Remove Join files
      file:
        path: $HOME/Master
        state: absent

    - name: Create share directory 
      file:
        path: /nfs_share
        state: directory
        mode: '0777'

    - name: Mount NFS 
      ansible.posix.mount:
        src: Storage-Server:/nfs
        path: /nfs_share
        opts: rw,sync
        state: mounted
        fstype: nfs