---
- name: Initialize Kubernetes Cluster
  hosts: k8s-master-lb
  vars:
    ansible_ip: 10.6.3.101
    ansible_port: 6443
  remote_user: root
  tasks:
    - name: 
      shell: kubeadm init --control-plane-endpoint=k8s-master-lb:6443 --upload-certs --pod-network-cidr=192.168.0.0/16 | tee ~/initial_log
