---
- name: Initialize Master Nodes
  hosts: k8s_nodes
  remote_user: root
  tasks:
    - name: Join Kubernetes Cluster as Master
      shell: kubeadm join 

    - name: Copy admin.conf to /.kube
      copy:
        src: /sources/admin.conf
        dest: $HOME/.kube/

    - name: Mount NFS 
      ansible.posix.monut:
        src: nfs_server:/nfs
        path: /nfs_share
        opts: rw,sync
        state: mounted
        fstype: nfs