---
- name: Set CNI for Kubernetes Cluster
  hosts: k8s_all
  gather_facts: no
  remote_user: root
  tasks:
    - name: Copy Calico.yml
      copy:
        src: /sources/calico.yaml
        dest: $HOME/

    - name: initialize Namespace
      shell: kubectl delete -f $HOME/calico.yaml
      ignore_errors: true
    
    - name: Install Calico
      shell: kubectl create -f $HOME/calico.yaml