---
- name: Initialize NFS Server
  hosts: nfs_server
  tasks:
    - name: Install NFS Utils
      yum:
        name: nfs-utils
        state: present

    - name: Create containerd directory
      file:
        path: /root/nfs
        state: directory
        mode: '0777' 

    - name: Configure NFS Server
      blockinfile:
        path: /etc/exports
        block: |
          /root/nfs 192.168.1.*(rw,sync)
          /root/nfs k8s*(rw,sync)

    - name: Enable Service
      systemd:
        name: nfs-server
        state: started
        enabled: yes