---
- name: Initialize system for install kubernetes
  hosts: k8s-all
  remote_user: root
  tasks:
    - name: set hosts file
      blockinfile:
        patch: /etc/hosts
        block: |
          10.6.3.101 k8s-master-lb
          10.6.3.110 k8s-master01
          10.6.3.120 k8s-master02
          10.6.3.130 k8s-master02
          10.6.3.111 k8s-node1-1
          10.6.3.112 k8s-node1-2
          10.6.3.121 k8s-node2-1
          10.6.3.122 k8s-node2-2
          10.6.3.131 k8s-node3-1
          10.6.3.132 k8s-node3-2
    - name: Disable Swap (1/2)
      shell: |
        swapoff -a
    - name: Disable Swap (2/2)
      replace: 
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Set Kernel Mode
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter
        create: true

    - name: Reload Kernel (1/2)
      modeprobe:
        name: overlay
    - name: Reload Kernel (2/2)
      modeprobe: 
        name: br_netfilter

    - name: Configure Kernel
      blockinfile:
        patch: /etc/sysctl.d/99-kubernetes-cri.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        create: true

    - name: Enable Kernel
      command: sysctl --system

    - name: Configure Kernel
      blockinfile:
        patch: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        create: true

    - name: Add ssh_connection trust
      blockinfile:
        patch: /etc/hosts.allow
        block: |
          sshd: 10.6.3.100
          sshd: 10.6.3.101
          sshd: 10.6.3.110
          sshd: 10.6.3.111
          sshd: 10.6.3.112
          sshd: 10.6.3.120
          sshd: 10.6.3.121
          sshd: 10.6.3.122
          sshd: 10.6.3.130
          sshd: 10.6.3.131
          sshd: 10.6.3.132

    - name: Deny Others
      blockinfile:
        patch: /etc/hosts.deny
        block: |
          sshd: ALL      